version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=senha123
      - DOCKER_INFLUXDB_INIT_ORG=esp32_org
      - DOCKER_INFLUXDB_INIT_BUCKET=health_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=senha
    restart: unless-stopped

  telegraf:
    image: telegraf:1.28
    container_name: telegraf
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - mosquitto
      - influxdb
    # Link para a rede do InfluxDB para poder se comunicar
    environment:
      - INFLUX_TOKEN=senha
    restart: unless-stopped

  backend:
    build: ./src
    container_name: backend
    ports:
      - "80:5000"
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=senha
      - INFLUXDB_ORG=esp32_org
      - INFLUXDB_BUCKET=health_data
    depends_on:
      - influxdb
    restart: unless-stopped

volumes:
  influxdb_data:
